### ISSUE TITLE
应用terminal配置后，光标消失

### ISSUE THREAD

**Issue by AlaricGilbert** [Jinkeycode/vscode-transparent-glow#1]
![此时，光标位于g与l之间](https://user-images.githubusercontent.com/36405110/57914373-16ea8400-78c1-11e9-82a9-1e211bf87f86.png)

![键入了一个字母f](https://user-images.githubusercontent.com/36405110/57914426-31246200-78c1-11e9-93fb-2113c124cbc9.png)

没有光标terminal的使用还是有点不便。

相关其他配置：
macOS、zsh、oh-my-zsh agnoster theme

**Comment by Jinkeycode** [comment]
已更新代码，请查看 https://github.com/Jinkeycode/vscode-transparent-glow/commit/937c355b3a0d43b0c27bd7574ff368b5c7367626

**Comment by liam61** [comment]
@Jinkeycode 终端想要复制输入的文字，勾选起来的部分和终端背景一样，不能很好的区分勾选到哪里了，能修复下吗
